services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: e_commerce_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        depends_on:
            db:
                condition: service_healthy
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: e_commerce_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: e_commerce_db
            MYSQL_USER: e_commerce_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 5s
            timeout: 5s
            retries: 10
        networks:
            - laravel_network
        
volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge